title: Ocean Car Service
baseURL: /
mediaTypes:
  application/json:
    delimiter: .
    suffixes:
    - json
  application/manifest+json:
    delimiter: .
    suffixes:
    - webmanifest
params:
  favicon: 'https://blazed.sirv.com/RTM/logo/ocs.png'
  header:
    title: Ocean Car Service
    has_nav: true
    nav_links:
      - label: Home
        url: /
      - label: About
        url: /about/
      - label: Booking
        url: /booking/
  footer:
    content: >-
      &copy; Ocean Car Service, RTM Transportation LLC. All rights reserved. Website by <a
      href="https://www.blazedlabs.com/" target="_blank">Blazed Labs</a>.
    has_social: true
    social_links:
      - label: Facebook
        url: 'https://www.facebook.com/oceancarservicellc'
        new_window: true
      - label: GitHub
        url: 'https://github.com/blazed-labs/oceancarservice-com'
        new_window: true
      - label: RTM
        url: 'https://rtmtransit.com/'
        new_window: true
    links: []
  domain: 'https://oceancarservice.com/'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
